package CSS.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new CSS_Declaration_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new CSS_Declaration_block_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CSS_File_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new CSS_Ruleset_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new CSS_Selector_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3878803ee0fa4e92L, 0xaead28bec22159e1L, 0x7a2187a2b23a422eL), MetaIdFactory.conceptId(0x3878803ee0fa4e92L, 0xaead28bec22159e1L, 0x7a2187a2b23a4234L), MetaIdFactory.conceptId(0x3878803ee0fa4e92L, 0xaead28bec22159e1L, 0x7a2187a2b23a4237L), MetaIdFactory.conceptId(0x3878803ee0fa4e92L, 0xaead28bec22159e1L, 0x7a2187a2b23a423cL), MetaIdFactory.conceptId(0x3878803ee0fa4e92L, 0xaead28bec22159e1L, 0x7a2187a2b23a423dL)).seal();
}
