package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Material extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Material() {
    super(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5dfeL, "Material", "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412222");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Maple_0 = new EnumerationDescriptor.MemberDescriptor("Maple", "wood", 0x7a2187a2b23c5e00L, "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412224");
  private final EnumerationDescriptor.MemberDescriptor myMember_Oak_0 = new EnumerationDescriptor.MemberDescriptor("Oak", "metal", 0x7a2187a2b23c5e03L, "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412227");
  private final EnumerationDescriptor.MemberDescriptor myMember_Iron_0 = new EnumerationDescriptor.MemberDescriptor("Iron", "iron", 0x7a2187a2b23c5e07L, "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412231");
  private final EnumerationDescriptor.MemberDescriptor myMember_Steel_0 = new EnumerationDescriptor.MemberDescriptor("Steel", "steel", 0x7a2187a2b23c5dffL, "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412223");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5dfeL, 0x7a2187a2b23c5e00L, 0x7a2187a2b23c5e03L, 0x7a2187a2b23c5e07L, 0x7a2187a2b23c5dffL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Maple_0, myMember_Oak_0, myMember_Iron_0, myMember_Steel_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Steel_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Maple":
        return myMember_Maple_0;
      case "Oak":
        return myMember_Oak_0;
      case "Iron":
        return myMember_Iron_0;
      case "Steel":
        return myMember_Steel_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
