package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Component = 0;
  public static final int Garage_Project = 1;
  public static final int Project_Component = 2;
  public static final int TextLine = 3;
  public static final int Warehouse = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L);
    builder.put(0x7a2187a2b23c5e16L, Component);
    builder.put(0x7a2187a2b23dc5b1L, Garage_Project);
    builder.put(0x7a2187a2b23dc5acL, Project_Component);
    builder.put(0x7a2187a2b23dc5a9L, TextLine);
    builder.put(0x7a2187a2b23c5dfdL, Warehouse);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
