package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptComponent = createDescriptorForComponent();
  /*package*/ final ConceptDescriptor myConceptGarage_Project = createDescriptorForGarage_Project();
  /*package*/ final ConceptDescriptor myConceptProject_Component = createDescriptorForProject_Component();
  /*package*/ final ConceptDescriptor myConceptTextLine = createDescriptorForTextLine();
  /*package*/ final ConceptDescriptor myConceptWarehouse = createDescriptorForWarehouse();
  /*package*/ final EnumerationDescriptor myEnumerationMaterial = new EnumerationDescriptor_Material();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeCode_Name = new ConstrainedStringDatatypeDescriptorImpl(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5a8L, "Code_Name", "r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703504296", "[@|#][A-Z][0-9]{3}");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptComponent, myConceptGarage_Project, myConceptProject_Component, myConceptTextLine, myConceptWarehouse);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Component:
        return myConceptComponent;
      case LanguageConceptSwitch.Garage_Project:
        return myConceptGarage_Project;
      case LanguageConceptSwitch.Project_Component:
        return myConceptProject_Component;
      case LanguageConceptSwitch.TextLine:
        return myConceptTextLine;
      case LanguageConceptSwitch.Warehouse:
        return myConceptWarehouse;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationMaterial, myCSDatatypeCode_Name);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Furniture", "Component", 0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5e16L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412246");
    b.version(2);
    b.property("material", 0x7a2187a2b23c5e19L).type(MetaIdFactory.dataTypeId(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5dfeL)).origin("8800464279703412249").done();
    b.property("price", 0x7a2187a2b23c5e1bL).type(PrimitiveTypeId.INTEGER).origin("8800464279703412251").done();
    b.alias("Component");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGarage_Project() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Furniture", "Garage_Project", 0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5b1L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703504305");
    b.version(2);
    b.property("code", 0x7a2187a2b23dc5b8L).type(MetaIdFactory.dataTypeId(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5a8L)).origin("8800464279703504312").done();
    b.aggregate("components", 0x7a2187a2b23dc5b6L).target(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5acL).optional(true).ordered(true).multiple(true).origin("8800464279703504310").done();
    b.aggregate("description", 0x7a2187a2b23dc5baL).target(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5a9L).optional(true).ordered(true).multiple(true).origin("8800464279703504314").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProject_Component() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Furniture", "Project_Component", 0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5acL);
    b.class_(false, false, false);
    b.origin("r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703504300");
    b.version(2);
    b.property("quantity", 0x7a2187a2b23dc5adL).type(PrimitiveTypeId.INTEGER).origin("8800464279703504301").done();
    b.associate("component", 0x7a2187a2b23dc5afL).target(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5e16L).optional(false).origin("8800464279703504303").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextLine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Furniture", "TextLine", 0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23dc5a9L);
    b.class_(false, false, false);
    b.origin("r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703504297");
    b.version(2);
    b.property("text", 0x7a2187a2b23dc5aaL).type(PrimitiveTypeId.STRING).origin("8800464279703504298").done();
    b.alias("Text line");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWarehouse() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Furniture", "Warehouse", 0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5dfdL);
    b.class_(false, false, true);
    b.origin("r:2c92cc35-8bc8-48c0-9d3a-aab697d09cf5(Furniture.structure)/8800464279703412221");
    b.version(2);
    b.aggregate("components", 0x7a2187a2b23c5e1eL).target(0xe2c2524837734879L, 0x8bfc859bbe4db0d8L, 0x7a2187a2b23c5e16L).optional(true).ordered(true).multiple(true).origin("8800464279703412254").done();
    b.alias("Warehouse");
    return b.create();
  }
}
