package HTML.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HtmlFile_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.document$qgEY));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink document$qgEY = MetaAdapterFactory.getContainmentLink(0xf1f3a555bd3a4398L, 0xaebb78c7c4134995L, 0x7a2187a2b23c3f19L, 0x7a2187a2b23c3f1cL, "document");
  }
}
