package Minesweeper.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import java.awt.EventQueue;

public class EasyMinesweeper extends JFrame {
  private JLabel statusbar;

  public EasyMinesweeper() {
    initUI();
  }

  private void initUI() {
    statusbar = new JLabel("");
    add(statusbar, BorderLayout.SOUTH);

    add(new EasyMinesweeperBoard(statusbar));

    setResizable(false);
    pack();

    setTitle("EasyMinesweeper");
    setLocationRelativeTo(null);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  }

  public static void main(String[] args) {
    EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        EasyMinesweeper ex = new EasyMinesweeper();
        ex.setVisible(true);
      }
    });
  }
}
