package common;

/*Generated by MPS */


public class GameStats {
  public int flags;
  public int lives;
  public int reveals;
  public int score;
  public int questionsCount;
  public int questionsAnswered;
}
