package common;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.border.Border;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import java.awt.Color;

public class Lesson {
  /*package*/ String title;
  /*package*/ String text;
  /*package*/ Boolean unlocked;
  /*package*/ int lessonHeight;
  /*package*/ final int titleFontSize = 16;
  /*package*/ final int textFontSize = 13;
  /*package*/ final int lessonWidth = 200;
  /*package*/ final int bottomPadding = 0;

  public Lesson(String title, String text) {
    this.title = title;
    this.text = text;
    lessonHeight = titleFontSize + textFontSize * (text.length() * textFontSize / lessonWidth) + bottomPadding;
  }

  public JPanel createLessonPanel() {
    JPanel panel = new JPanel();
    Border border;
    panel.setLayout(new BorderLayout());
    JLabel titleLable = new JLabel(title);
    Font font;
    // Edit the look of the lesson title here: 
    font = new Font(Font.SANS_SERIF, Font.BOLD, titleFontSize);
    titleLable.setFont(font);
    panel.add(titleLable, BorderLayout.NORTH);
    JMultilineLabel textArea = new JMultilineLabel(text);
    // Edit the look of the text here: 
    font = new Font(Font.SANS_SERIF, Font.PLAIN, textFontSize);
    textArea.setFont(font);
    panel.add(textArea, BorderLayout.CENTER);
    // Edit the look of the panel: 
    panel.setPreferredSize(new Dimension(lessonWidth, lessonHeight));
    border = BorderFactory.createLineBorder(Color.BLACK);
    panel.setBorder(border);
    return panel;
  }

  public int getLessonHeight() {
    return lessonHeight;
  }
}
