package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class homework extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.blue);
      graphics.drawOval(100, 200, 50, 50);
      graphics.setColor(Color.gray);
      graphics.drawRect(40, 80, 90, 90);
      graphics.setColor(Color.green);
      graphics.drawOval(200, 200, 50, 50);
    }
  };

  public void initialize() {
    this.setTitle("homework");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    homework canvas = new homework();
    canvas.initialize();
  }
}
