package vu.mif.calculator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class HackCalk extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }

    public void removeUpdate(DocumentEvent p0) {
      update();
    }

    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };

  private JTextField inputField_a_0 = new JTextField();
  private JTextField inputField_b_0 = new JTextField();
  private JTextField inputField_c_0 = new JTextField();
  private JTextField outputField_a_0 = new JTextField();

  public HackCalk() {
    setTitle("HackCalk");
    setLayout(new GridLayout(0, 2));
    inputField_a_0.getDocument().addDocumentListener(listener);
    add(new JLabel("aaaaa"));
    add(inputField_a_0);
    inputField_b_0.getDocument().addDocumentListener(listener);
    add(new JLabel("bbbbb"));
    add(inputField_b_0);
    inputField_c_0.getDocument().addDocumentListener(listener);
    add(new JLabel("ccccc"));
    add(inputField_c_0);
    add(new JLabel("Output"));
    add(outputField_a_0);
    update();
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public void update() {
    int i_a_0 = 0;
    int i_b_0 = 0;
    int i_c_0 = 0;
    try {
      i_a_0 = Integer.parseInt(inputField_a_0.getText());
      i_b_0 = Integer.parseInt(inputField_b_0.getText());
      i_c_0 = Integer.parseInt(inputField_c_0.getText());
    } catch (NumberFormatException e) {
    }
    outputField_a_0.setText("" + ((i_a_0 == i_b_0 ? 2 : 4)));
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new HackCalk();
      }
    });
  }
}
